pip install pypylon
pip install PyQt5
pip install sys
pip install opencv-python
pip install numpy
pip install qdarkstyle
pip install device
pip install pickle
pip install math
pip install datetime
pip install threading
pip install random
pip install io
pip install PIL
pip install serial
pip install pyserial
pip install pyfirmata
pip install matplotlib
pip install imageio
pip install pyyaml
pip install queue
pip install os
pip install time
pip install glob
pip install scipy
pip install subprocess
pip install shutil