# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalyzeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalyzeWindow(object):
    def setupUi(self, AnalyzeWindow):
        AnalyzeWindow.setObjectName("AnalyzeWindow")
        AnalyzeWindow.resize(676, 477)
        self.centralwidget = QtWidgets.QWidget(AnalyzeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_loadCube = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_loadCube.setObjectName("pushButton_loadCube")
        self.gridLayout.addWidget(self.pushButton_loadCube, 2, 0, 1, 1)
        self.label_waveLength = QtWidgets.QLabel(self.centralwidget)
        self.label_waveLength.setObjectName("label_waveLength")
        self.gridLayout.addWidget(self.label_waveLength, 4, 5, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.widget_Plot = QtWidgets.QWidget(self.centralwidget)
        self.widget_Plot.setObjectName("widget_Plot")
        self.verticalLayout.addWidget(self.widget_Plot)
        self.gridLayout.addLayout(self.verticalLayout, 5, 0, 1, 6)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 4, 0, 1, 5)
        self.label_Image = QtWidgets.QLabel(self.centralwidget)
        self.label_Image.setText("")
        self.label_Image.setObjectName("label_Image")
        self.gridLayout.addWidget(self.label_Image, 3, 0, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.pushButton_RGBStat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_RGBStat.setObjectName("pushButton_RGBStat")
        self.gridLayout.addWidget(self.pushButton_RGBStat, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        AnalyzeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AnalyzeWindow)
        self.statusbar.setObjectName("statusbar")
        AnalyzeWindow.setStatusBar(self.statusbar)
        self.actionExport_Cube = QtWidgets.QAction(AnalyzeWindow)
        self.actionExport_Cube.setObjectName("actionExport_Cube")
        self.actionExport_Pickle = QtWidgets.QAction(AnalyzeWindow)
        self.actionExport_Pickle.setObjectName("actionExport_Pickle")
        self.actionExport_Matlab = QtWidgets.QAction(AnalyzeWindow)
        self.actionExport_Matlab.setObjectName("actionExport_Matlab")

        self.retranslateUi(AnalyzeWindow)
        QtCore.QMetaObject.connectSlotsByName(AnalyzeWindow)

    def retranslateUi(self, AnalyzeWindow):
        _translate = QtCore.QCoreApplication.translate
        AnalyzeWindow.setWindowTitle(_translate("AnalyzeWindow", "MainWindow"))
        self.pushButton_loadCube.setText(_translate("AnalyzeWindow", "Load Cube"))
        self.label_waveLength.setText(_translate("AnalyzeWindow", "Wave Length : 400 nm"))
        self.pushButton_RGBStat.setText(_translate("AnalyzeWindow", "RGB"))
        self.actionExport_Cube.setText(_translate("AnalyzeWindow", "Export Cube"))
        self.actionExport_Pickle.setText(_translate("AnalyzeWindow", "Export Pickle"))
        self.actionExport_Matlab.setText(_translate("AnalyzeWindow", "Export Matlab"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnalyzeWindow = QtWidgets.QMainWindow()
    ui = Ui_AnalyzeWindow()
    ui.setupUi(AnalyzeWindow)
    AnalyzeWindow.show()
    sys.exit(app.exec_())
